In [6]:
# imports for nba api
from nba_api.stats.endpoints import playoffpicture
from nba_api.stats.static import teams
from IPython.display import display
import requests
import json

while True:
    try:
        # Getting team name for searching
        team_name = input("Please enter the team name or type 'q' to quit: ")
        if team_name.lower() == 'q':
            print("You quit the program")
            break
        team = teams.find_teams_by_full_name(team_name)
        # Getting team info and team id
        if len(team) == 0:
            print("You entered an incorrect team name")
        else:
            team = team[0]
            team_id = int(team['id'])
            # Pulling data from api and putting it into a dataframe
            data_2019 = playoffpicture.PlayoffPicture(league_id="00", season_id="22018")
            data_2018 = playoffpicture.PlayoffPicture(league_id="00", season_id="22017")
            df_2018 = data_2018.get_data_frames()
            df_2019 = data_2019.get_data_frames()
            # Getting the data out from the response
            east_2019 = df_2019[2]
            west_2019 = df_2019[3]
            east_2018 = df_2018[2]
            west_2018 = df_2018[3]
            # Checking to see if the team id is in both years for east
            if team_id in east_2019['TEAM_ID'].values and team_id in east_2018['TEAM_ID'].values:
                print("East 2018 Seeds:")
                display(east_2018)
                print("East 2019 Seeds:")
                display(east_2019)
                team_info_2019 = east_2019[east_2019['TEAM_ID'] == team_id]
                team_info_2018 = east_2018[east_2018['TEAM_ID'] == team_id]
                if team_info_2019[['RANK']].values[0][0] < 8 and team_info_2018[['RANK']].values[0][0] < 8:
                    print("Your team might do GOOD this coming year!(This is based on the 2018-2019 data from both playoffs")
                else:
                    print("Your team might do BAD this coming year! (This is based on the 2018-2019 data from both playoffs)", )
            # Checking to see if the team id is in both years for west
            elif team_id in west_2019['TEAM_ID'].values and team_id in west_2018['TEAM_ID'].values:
                print("West 2018 Seeds:")
                display(west_2018)
                print("West 2019 Seeds:")
                display(west_2019)
                team_info_2019 = west_2019[west_2019['TEAM_ID'] == team_id]
                team_info_2018 = west_2018[west_2018['TEAM_ID'] == team_id]
                if team_info_2019[['RANK']].values[0][0] < 8 and team_info_2018[['RANK']].values[0][0] < 8:
                    print("Your team has a high chance of making it to the playoffs this coming year!")
                else:
                    print("Your team might do BAD this coming year!(This is based on the 2018-2019 data from both playoffs")
            else:
                print("That team didn't make the playoffs.(This is based on the 2018-2019 data from both playoffs")
    except json.decoder.JSONDecodeError as e: 
        print("ERROR: Cannot decode the response into json")
        print("DETAILS", e)
    # response not ok
    except requests.exceptions.HTTPError as e:
        print("ERROR: Response from ", url, 'was not ok.')
        print("DETAILS:", e)
    # internet is broken
    except requests.exceptions.RequestException as e: 
        print("ERROR: Cannot connect to ", url)
        print("DETAILS:", e)

Please enter the team name or type 'q' to quit: Knicks
East 2018 Seeds:

,CONFERENCE,RANK,TEAM,TEAM_ID,WINS,LOSSES,PCT,DIV,CONF,HOME,...,GR_OVER_500_AWAY,GR_UNDER_500,GR_UNDER_500_HOME,GR_UNDER_500_AWAY,RANKING_CRITERIA,CLINCHED_PLAYOFFS,CLINCHED_CONFERENCE,CLINCHED_DIVISION,ELIMINATED_PLAYOFFS,SOSA_REMAINING
0,East,1,Toronto,1610612761,59,23,0.720,12-4,40-12,34-7,...,0,0,0,0,0,1,1,1,0,None
1,East,2,Boston,1610612738,55,27,0.671,12-4,33-19,27-14,...,0,0,0,0,0,1,0,0,0,None
2,East,3,Philadelphia,1610612755,52,30,0.634,9-7,34-18,30-11,...,0,0,0,0,0,1,0,0,0,None
3,East,4,Cleveland,1610612739,50,32,0.610,11-5,35-17,29-12,...,0,0,0,0,0,1,0,1,0,None
4,East,5,Indiana,1610612754,48,34,0.585,10-6,32-20,27-14,...,0,0,0,0,0,1,0,0,0,None
5,East,6,Miami,1610612748,44,38,0.537,11-5,31-21,26-15,...,0,0,0,0,1,1,0,1,0,None
6,East,7,Milwaukee,1610612749,44,38,0.537,6-10,27-25,25-16,...,0,0,0,0,0,1,0,0,0,None
7,East,8,Washington,1610612764,43,39,0.524,8-8,28-24,23-18,...,0,0,0,0,0,1,0,0,0,None
8,East,9,Detroit,1610612765,39,43,0.476,9-7,24-28,25-16,...,0,0,0,0,0,0,0,0,1,None
9,East,10,Charlotte,1610612766,36,46,0.439,11-5,22-30,21-20,...,0,0,0,0,0,0,0,0,1,None
10,East,11,New York,1610612752,29,53,0.354,6-10,17-35,19-22,...,0,0,0,0,0,0,0,0,1,None
11,East,12,Brooklyn,1610612751,28,54,0.341,1-15,19-33,15-26,...,0,0,0,0,0,0,0,0,1,None
12,East,13,Chicago,1610612741,27,55,0.329,4-12,21-31,17-24,...,0,0,0,0,0,0,0,0,1,None
13,East,14,Orlando,1610612753,25,57,0.305,5-11,15-37,17-24,...,0,0,0,0,0,0,0,0,1,None
14,East,15,Atlanta,1610612737,24,58,0.293,5-11,12-40,16-25,...,0,0,0,0,0,0,0,0,1,None

East 2019 Seeds:

,CONFERENCE,RANK,TEAM,TEAM_ID,WINS,LOSSES,PCT,DIV,CONF,HOME,...,GR_OVER_500_AWAY,GR_UNDER_500,GR_UNDER_500_HOME,GR_UNDER_500_AWAY,RANKING_CRITERIA,CLINCHED_PLAYOFFS,CLINCHED_CONFERENCE,CLINCHED_DIVISION,ELIMINATED_PLAYOFFS,SOSA_REMAINING
0,East,1,Milwaukee,1610612749,60,22,0.732,14-2,40-12,33-8,...,0,0,0,0,0,1,1,1,0,None
1,East,2,Toronto,1610612761,58,24,0.707,12-4,36-16,32-9,...,0,0,0,0,0,1,0,1,0,None
2,East,3,Philadelphia,1610612755,51,31,0.622,8-8,31-21,31-10,...,0,0,0,0,0,1,0,0,0,None
3,East,4,Boston,1610612738,49,33,0.598,10-6,35-17,28-13,...,0,0,0,0,0,1,0,0,0,None
4,East,5,Indiana,1610612754,48,34,0.585,11-5,33-19,29-12,...,0,0,0,0,0,1,0,0,0,None
5,East,6,Brooklyn,1610612751,42,40,0.512,8-8,29-23,23-18,...,0,0,0,0,1,1,0,0,0,None
6,East,7,Orlando,1610612753,42,40,0.512,10-6,30-22,25-16,...,0,0,0,0,0,1,0,1,0,None
7,East,8,Detroit,1610612765,41,41,0.500,8-8,27-25,26-15,...,0,0,0,0,0,1,0,0,0,None
8,East,9,Charlotte,1610612766,39,43,0.476,10-6,29-23,25-16,...,0,0,0,0,3,0,0,0,1,None
9,East,10,Miami,1610612748,39,43,0.476,7-9,23-29,19-22,...,0,0,0,0,0,0,0,0,1,None
10,East,11,Washington,1610612764,32,50,0.390,7-9,19-33,22-19,...,0,0,0,0,0,0,0,0,1,None
11,East,12,Atlanta,1610612737,29,53,0.354,6-10,16-36,17-24,...,0,0,0,0,0,0,0,0,1,None
12,East,13,Chicago,1610612741,22,60,0.268,3-13,16-36,9-32,...,0,0,0,0,0,0,0,0,1,None
13,East,14,Cleveland,1610612739,19,63,0.232,4-12,15-37,13-28,...,0,0,0,0,0,0,0,0,1,None
14,East,15,New York,1610612752,17,65,0.207,2-14,11-41,9-32,...,0,0,0,0,0,0,0,0,1,None

Your team might do BAD this coming year! (This is based on the 2018-2019 data from both playoffs)
Please enter the team name or type 'q' to quit: bveevd
You entered an incorrect team name
Please enter the team name or type 'q' to quit: q
You quit the program